import downArrow from "./down-arrow"

export default {
  button: {
    color: "white",
    backgroundColor: "secondary",
    background: "secondary",
    borderColor: "secondary",
    padding: "0 24px",
    width: "100%",
    border: "none",
    cursor: "pointer",
    display: "inline-block",
    textAlign: "center",
    textTransform: "uppercase",
    borderRadius: "2px",
    fontSize: "12px",
    fontWeight: "600",
    height: "44px",
    lineHeight: "40px",
    border: "2px solid transparent",
    transition: "all 260ms ease-in-out",
    ":focus": {
      outline: 0,
    },
    ":hover": {
      outline: 0,
      background: "primary",
      backgroundColor: "primary",
    },
  },
  select: {
    display: "block",
    width: "100%",
    height: "38px",
    padding: "8px 12px",
    fontSize: "14px",
    lineHeight: "1.42857",
    color: "#414143",
    backgroundColor: "#fff",
    backgroundImage: url(downArrow),
    backgroundSize: "12px",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "97%",
    border: "1px solid #44bc8f",
    borderRadius: "0px",
    boxShadow: "inset 0 1px 1px rgba(0, 0, 0, 0.075)",
    transition: "border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s",
  },
  input: {
    height: "38px",
    width: "100%",
    padding: "8px",
    backgroundColor: "#fff",
    borderRadius: "3px",
    outline: "none",
    border: 0,
    border: "0px solid",
    transition: "border 0.1s ease-in",
    fontSize: "12px",
    color: "gray",
  },
}
